const appCodes = {
  "ADR_Recipe": "AR",
  "ai_Chat": "ChatA1",
  "ai_Chat_IOS": "ChatI1",
  "AND_AI_Learn": "LearnA1",
  "Android_AI_Chat": "ChatA1",
  "Android_AI_Chat_IAP": "ChatA2",
  "Android_AI_Chat_Lumos": "ChatA3",
  "Android_AI_Home": "HomeA1",
  "Android_AI_Learn": "LearnA1",
  "Android_AI_Photo": "PhotoA1",
  "android_arteria_blood_pressure": "AABP",
  "Android_Arteria_Blood_Pressure": "AABP",
  "Android_Authenticator": "AuthA1",
  "Android_Blood_Presure": "AABP",
  "Android_Cast_Glitter": "TVI2",
  "Android_Chat_AI_IAA_2": "ChatA3",
  "Android_Chat_AI_IAP": "ChatA2",
  "Android_Clean_2": "CleanA2",
  "Android_Face_Scan": "AFS",
  "android_face_scanner": "AFS",
  "Android_Glitter": "TVI2",
  "android_glucera_blood_sugar": "AGLBS",
  "Android_Heart_Rate": "HRA1",
  "Android_iCardiac": "HRA1",
  "Android_LumosAI": "ChatA3",
  "Android_PDF_3": "PDFA3",
  "Android_Printer": "PrintA1",
  "Android_Remote_Roku_Org": "TVA1",
  "Android_Translate_2": "ATA2",
  "Android_Translate_All_2": "ATA2",
  "Android_WO": "WOA1",
  "Android_Word_Office": "WOA1",
  "Authenticator App": "AuthI1",
  "Begamob_Document": "DocA1",
  "Blood_Pressure": "IABP",
  "Calorie": "CaloI1",
  "cast_glitter": "TVI2",
  "Cast_Remote_TV": "TVI1",
  "Clean Android": "CleanA1",
  "Clean Android 2": "CleanA2",
  "Clean_Android": "CleanA1",
  "Clean_IOS": "CleanI1",
  "DramaOn": "D2",
  "DramaOn_iOS": "DI",
  "Health_Yoga_Master_iOS": "HRI2",
  "iOS_ai_Chat": "ChatI1",
  "iOS_AI_Home": "AHI",
  "IOS_AI_Learn": "LearnI1",
  "iOS_AI_Photo": "PhotoI1",
  "ios_arteria_blood_pressure": "IABP",
  "iOS_Arteria_BloodPressure": "IABP",
  "iOS_Authenticator": "AuthI1",
  "IOS_Authenticator_2FA": "AuthI2",
  "ios_begamob_car_widget": "Car1",
  "iOS_Blood_Presure": "IABP",
  "iOS_Calorie": "CaloI1",
  "iOS_Car_Widget": "Car1",
  "iOS_Clean_iOS": "CleanI1",
  "IOS_Face_Scan": "IFS",
  "ios_face_scanner": "IFS",
  "iOS_FaceScan": "IFS",
  "ios_find_my_device_vip": "FindI1",
  "iOS_FindMy": "FindI1",
  "ios_glucera_blood_sugar": "IGLBS",
  "iOS_Heart Rate 4": "HRI2",
  "iOS_Heart_Rate": "HRI1",
  "iOS_iCardiac": "HRI1",
  "iOS_Printer": "PrintI1",
  "iOS_QR_Code": "QR1",
  "iOS_QRCode": "QR1",
  "iOS_Recipe": "IR",
  "IOS_Recipe": "IR",
  "iOS_Remote_iOS": "TVI1",
  "iOS_Remote_Roku": "TVI2",
  "iOS_Remote_Roku_2": "TVI2",
  "ios_screen_mirror": "MirI1",
  "ios_stresswatch_2": "IST",
  "iOS_Sub_Manager": "SMI1",
  "iOS_TCG_Card_Identifier": "ICI1",
  "ios_tcg_identify_card": "ICI1",
  "iOS_Translate": "TranI1",
  "IOS_Word_Office": "WOI1",
  "NextNovels": "DI",
  "PDF_Reader_PDF_Editor": "PDFA3",
  "Remote_Org_2": "TVA1",
  "Stress watch": "IST",
  "Sub Manager iOS": "SMI1",
  "Web_Recipe": "WR",
  "Word Office iOS": "WOI1",
  "Word_Office": "WOA1",
} as const;

export default appCodes;
